//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PG()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int id { get; set; }
        public string User_Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> Phone_Number { get; set; }
        public string Status { get; set; }
        public Nullable<int> admin_id { get; set; }
        public string CategoryName { get; set; }
        /* [Display(Name="img")]
           public HttpPostedFileBase CategoryName { get; set; }
       */
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
    }
}
